# Generated by Django 4.1 on 2022-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('post', 'POST'), ('get', 'GET'), ('delete', 'DELETE'), ('put', 'PUT')], max_length=10, verbose_name='Method')),
                ('url', models.URLField(verbose_name='URL')),
                ('response', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=75, verbose_name='Author')),
                ('head', models.CharField(max_length=75, verbose_name='Headline')),
                ('resume', models.CharField(max_length=250, verbose_name='Resume')),
                ('content', models.CharField(max_length=2500, verbose_name='Content')),
            ],
        ),
    ]
