# Generated by Django 4.1 on 2022-08-18 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_news_publiseddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publisedDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Published At'),
        ),
    ]
